In [ ]:
#What is overfitting is 
#Overfiting happens when a model learns the trainng

In [ ]:
# high accuracy 
# poor performance

# How to fix

# use more data 
# apply regularization
# simplyfy model
# cross validation or dropout

In [ ]:
# Underfitting
# When  model is too simple to capture underlaying pattern then underfitting occurs

# Poor Performance 
# Use more complex model 
# add relevant feature 
# train longer 
# reduce regularization


# formula for under fitting
# y= XPower 2+2x+1(Underfiting)

# overfiting
#  y =a base 0 + a base 1 x+a base 2 x** 2+ .....(overfiting)

In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv(r'C:\Users\ajayt\OneDrive\Desktop\DataSets\iris.csv', names=['sl','sw','pl','pw','classes'])
x_test=data

In [3]:
data.head()

    sl   sw   pl   pw classes
0  5.1  3.5  1.4  0.2  setosa
1  4.9  3.0  1.4  0.2  setosa
2  4.7  3.2  1.3  0.2  setosa
3  4.6  3.1  1.5  0.2  setosa
4  5.0  3.6  1.4  0.2  setosa

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2)

NameError: name 'y' is not defined

In [5]:
data.shape

(150, 5)

In [20]:
x=data.iloc[:,0:4]

In [21]:
x.head()

    sl   sw   pl   pw
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [21]:
y=data.iloc[:,4:5]

In [22]:
y

NameError: name 'y' is not defined

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y ,test_size=.2,random_state=10)

NameError: name 'y' is not defined

In [27]:
y_train.shape

(120, 1)

In [29]:
x_test.shape

(30, 4)

In [17]:
y_test.shape

NameError: name 'y_test' is not defined

In [18]:
x_train.head()

NameError: name 'x_train' is not defined

In [9]:
# K nebhougher clasifier
knn = KNeighborsClassifier(n_neighbors=5)

In [16]:
knn.fit(x_train,y_train)

NameError: name 'x_train' is not defined

In [33]:
pred = knn.predict(x_test)

In [13]:
pred

NameError: name 'pred' is not defined

In [11]:
print(accuracy_score(y_test,pred))

NameError: name 'y_test' is not defined

In [12]:
confusion_matrix(y_test,pred)

NameError: name 'y_test' is not defined

In [38]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.92      0.96        13
   virginica       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

In [14]:
!pip install flask

Collecting flask
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: blinker>=1.9.0 in C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages (from flask) (8.1.8)
Requirement already satisfied: itsdangerous>=2.2.0 in C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages (from flask) (3.0.3)
Collecting werkzeug>=3.1.0 (from flask)
  Downloading werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: colorama in C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages (from click>=8.1.3->flask) (0.4.6)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Downloading werkzeug-3.1.8-py3-none-any.whl (226 kB)
Installing collected packages: werkzeug, flask

   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   ---------------------------------------- 0/2 [werkzeug]
   -------------------- ------------------- 1/2 [flask]
   -------------------- ------------------- 1/2 [flask]
   -------------------- ------------------- 1/2 [flask]
   -------------------- ------------------- 1/2 [flask]
   -------------------- ------------------- 1/2 [flask]
   -------------------- ------------------- 1/2 [flask]
   -------------------- ------------------- 1/2 [flask]
   -------------------- ------------------- 1/2 [flask]
   ---------------------------------------- 2/2 [flask]

Successfully installed flask-3.1.3 werkzeug-3.1.8